### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Daxia1234567** [GGWPXXXX/Flare-Watcher#1]
May I ask if you could share the dataset? My course assignment requires the use of synchronized fire images and sensor data. I would greatly appreciate it if you could share it!

**Comment by Daxia1234567** [comment]
I'm sorry I didn't make it clear. I'm not going to use your code directly, I'm just looking for a dataset that meets the requirements. Your research subject happens to be quite similar to mine.

**Comment by GGWPXXXX** [comment]
Sure, here are the sensor [dataset](https://www.kaggle.com/datasets/deepcontractor/smoke-detection-dataset) and this is object detection [dataset](https://universe.roboflow.com/fire-test/fire-detection-ijcxg)

**Comment by Daxia1234567** [comment]
Thank you very much! Wishing you all the best!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Pattadon ***@***.***&gt;; 
发送时间: 2024年4月22日(星期一) 晚上9:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [GGWPXXXX/Flare-Watcher] Dataset (Issue #1)














 
Sure, here are the sensor dataset and this is object detection dataset
